import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-carousel-prime',
  templateUrl: './carousel-prime.component.html',
  styleUrls: ['./carousel.css']
})
export class CarouselPrimeComponent implements OnInit {
  cars: any[];
  constructor() { 
    this.cars = vehilelist
  }

  ngOnInit() {
  }

}
export const vehilelist = [
  {     
       'vin': '3FAHP0HA1AR151111',
       'vehicle_id': '403956904',
       'year': undefined,
       'make': '',
       'model': 'Fusion',
       'trim': 'SE',
       'vehicle_grade': null,
       'mileage': 54321,
       'driveTrain': 'FRONT WHEEL DRIVE',
       'exterior_color': 'RED CANDY ',
       'thumbnail': 'assets/Desert.jpg',
       'binPrice': 8100,
       'current_max_bid': 8000,
       'cost_to_market': 0.8449684507684836,
       'market_day_supply_mmy': 13.636363636363637,
       'current_dealer_supply': null,
       'avg_dealer_type_inv_cnt_mmy': 0.1,
       'seller': 'SANTANDER (CAP)',
       'state': 'TX',
       'zip': '77047',
       'auction_vendor': 'TERTT',
       'interiorColor': 'CHARCOAL BLACK',
       'vehicle_status': {
           'status_name': 'SOLD'             
       },       
      'atc_org_id': '186363',     
       'reason_id': '3',
       'reason_description': 'You are low on this MMY compared to your lot average over the past 90 days.',
       'reason_badge': 'https://assets.drivindealer.com/images/badges/low_lot_supply.png',
       'reason_name': 'Low Lot Supply'     
},
{     
  'vin': '3FAHP0HA1AR151221',
  'vehicle_id': '403956904',
  'year': undefined,
  'make': '',
  'model': 'Fusion',
  'trim': 'SE',
  'vehicle_grade': null,
  'mileage': 12345,
  'driveTrain': 'FRONT WHEEL DRIVE',
  'exterior_color': 'RED CANDY ',
  'thumbnail': 'assets/Koala.jpg',
  'binPrice': 8100,
  'current_max_bid': 8000,
  'cost_to_market': 0.8449684507684836,
  'market_day_supply_mmy': 13.636363636363637,
  'current_dealer_supply': null,
  'avg_dealer_type_inv_cnt_mmy': 0.1,
  'seller': 'SANTANDER (CAP)',
  'state': 'TX',
  'zip': '77047',
  'auction_vendor': 'ADESA',
  'interiorColor': 'CHARCOAL BLACK',
  'vehicle_status': {
      'status_name': 'SOLD'             
  },       
 'atc_org_id': '186363',     
  'reason_id': '3',
  'reason_description': 'You are low on this MMY compared to your lot average over the past 90 days.',
  'reason_badge': 'https://assets.drivindealer.com/images/badges/low_lot_supply.png',
  'reason_name': 'Low Lot Supply'     
},
{     
  'vin': '3FAHP0HA1AR151221',
  'vehicle_id': '403956904',
  'year': undefined,
  'make': '',
  'model': 'Fusion',
  'trim': 'SE',
  'vehicle_grade': null,
  'mileage': 2222,
  'driveTrain': 'FRONT WHEEL DRIVE',
  'exterior_color': 'RED CANDY ',
  'thumbnail': 'assets/Lighthouse.jpg',
  'binPrice': 8100,
  'current_max_bid': 8000,
  'cost_to_market': 0.8449684507684836,
  'market_day_supply_mmy': 13.636363636363637,
  'current_dealer_supply': null,
  'avg_dealer_type_inv_cnt_mmy': 0.1,
  'seller': 'SANTANDER (CAP)',
  'state': 'TX',
  'zip': '77047',
  'auction_vendor': 'UYTYR',
  'interiorColor': 'CHARCOAL BLACK',
  'vehicle_status': {
      'status_name': 'SOLD'             
  },       
 'atc_org_id': '186363',     
  'reason_id': '3',
  'reason_description': 'You are low on this MMY compared to your lot average over the past 90 days.',
  'reason_badge': 'https://assets.drivindealer.com/images/badges/low_lot_supply.png',
  'reason_name': 'Low Lot Supply'     
},
{     
 'vin': '3FAHP0HA1AR151221',
 'vehicle_id': '403956904',
 'year': undefined,
 'make': '',
 'model': 'Fusion',
 'trim': 'SE',
 'vehicle_grade': null,
 'mileage': 12345,
 'driveTrain': 'FRONT WHEEL DRIVE',
 'exterior_color': 'RED CANDY ',
 'thumbnail': 'assets/Penguins.jpg',
 'binPrice': 8100,
 'current_max_bid': 8000,
 'cost_to_market': 0.8449684507684836,
 'market_day_supply_mmy': 13.636363636363637,
 'current_dealer_supply': null,
 'avg_dealer_type_inv_cnt_mmy': 0.1,
 'seller': 'SANTANDER (CAP)',
 'state': 'TX',
 'zip': '77047',
 'auction_vendor': 'ADESA',
 'interiorColor': 'CHARCOAL BLACK',
 'vehicle_status': {
     'status_name': 'SOLD'             
 },       
'atc_org_id': '186363',     
 'reason_id': '3',
 'reason_description': 'You are low on this MMY compared to your lot average over the past 90 days.',
 'reason_badge': 'https://assets.drivindealer.com/images/badges/low_lot_supply.png',
 'reason_name': 'Low Lot Supply'     
},
{     
  'vin': '3FAHP0HA1AR151111',
  'vehicle_id': '403956904',
  'year': undefined,
  'make': '',
  'model': 'Fusion',
  'trim': 'SE',
  'vehicle_grade': null,
  'mileage': 54321,
  'driveTrain': 'FRONT WHEEL DRIVE',
  'exterior_color': 'RED CANDY ',
  'thumbnail': 'assets/Desert.jpg',
  'binPrice': 8100,
  'current_max_bid': 8000,
  'cost_to_market': 0.8449684507684836,
  'market_day_supply_mmy': 13.636363636363637,
  'current_dealer_supply': null,
  'avg_dealer_type_inv_cnt_mmy': 0.1,
  'seller': 'SANTANDER (CAP)',
  'state': 'TX',
  'zip': '77047',
  'auction_vendor': 'TERTT',
  'interiorColor': 'CHARCOAL BLACK',
  'vehicle_status': {
      'status_name': 'SOLD'             
  },       
 'atc_org_id': '186363',     
  'reason_id': '3',
  'reason_description': 'You are low on this MMY compared to your lot average over the past 90 days.',
  'reason_badge': 'https://assets.drivindealer.com/images/badges/low_lot_supply.png',
  'reason_name': 'Low Lot Supply'     
},
{     
  'vin': '3FAHP0HA1AR151111',
  'vehicle_id': '403956904',
  'year': undefined,
  'make': '',
  'model': 'Fusion',
  'trim': 'SE',
  'vehicle_grade': null,
  'mileage': 54321,
  'driveTrain': 'FRONT WHEEL DRIVE',
  'exterior_color': 'RED CANDY ',
  'thumbnail': 'assets/Desert.jpg',
  'binPrice': 8100,
  'current_max_bid': 8000,
  'cost_to_market': 0.8449684507684836,
  'market_day_supply_mmy': 13.636363636363637,
  'current_dealer_supply': null,
  'avg_dealer_type_inv_cnt_mmy': 0.1,
  'seller': 'SANTANDER (CAP)',
  'state': 'TX',
  'zip': '77047',
  'auction_vendor': 'TERTT',
  'interiorColor': 'CHARCOAL BLACK',
  'vehicle_status': {
      'status_name': 'SOLD'             
  },       
 'atc_org_id': '186363',     
  'reason_id': '3',
  'reason_description': 'You are low on this MMY compared to your lot average over the past 90 days.',
  'reason_badge': 'https://assets.drivindealer.com/images/badges/low_lot_supply.png',
  'reason_name': 'Low Lot Supply'     
}
,
{     
  'vin': '3FAHP0HA1AR151111',
  'vehicle_id': '403956904',
  'year': undefined,
  'make': '',
  'model': 'Fusion',
  'trim': 'SE',
  'vehicle_grade': null,
  'mileage': 54321,
  'driveTrain': 'FRONT WHEEL DRIVE',
  'exterior_color': 'RED CANDY ',
  'thumbnail': 'assets/Desert.jpg',
  'binPrice': 8100,
  'current_max_bid': 8000,
  'cost_to_market': 0.8449684507684836,
  'market_day_supply_mmy': 13.636363636363637,
  'current_dealer_supply': null,
  'avg_dealer_type_inv_cnt_mmy': 0.1,
  'seller': 'SANTANDER (CAP)',
  'state': 'TX',
  'zip': '77047',
  'auction_vendor': 'TERTT',
  'interiorColor': 'CHARCOAL BLACK',
  'vehicle_status': {
      'status_name': 'SOLD'             
  },       
 'atc_org_id': '186363',     
  'reason_id': '3',
  'reason_description': 'You are low on this MMY compared to your lot average over the past 90 days.',
  'reason_badge': 'https://assets.drivindealer.com/images/badges/low_lot_supply.png',
  'reason_name': 'Low Lot Supply'     
}
,
{     
  'vin': '3FAHP0HA1AR151111',
  'vehicle_id': '403956904',
  'year': undefined,
  'make': '',
  'model': 'Fusion',
  'trim': 'SE',
  'vehicle_grade': null,
  'mileage': 54321,
  'driveTrain': 'FRONT WHEEL DRIVE',
  'exterior_color': 'RED CANDY ',
  'thumbnail': 'assets/Desert.jpg',
  'binPrice': 8100,
  'current_max_bid': 8000,
  'cost_to_market': 0.8449684507684836,
  'market_day_supply_mmy': 13.636363636363637,
  'current_dealer_supply': null,
  'avg_dealer_type_inv_cnt_mmy': 0.1,
  'seller': 'SANTANDER (CAP)',
  'state': 'TX',
  'zip': '77047',
  'auction_vendor': 'TERTT',
  'interiorColor': 'CHARCOAL BLACK',
  'vehicle_status': {
      'status_name': 'SOLD'             
  },       
 'atc_org_id': '186363',     
  'reason_id': '3',
  'reason_description': 'You are low on this MMY compared to your lot average over the past 90 days.',
  'reason_badge': 'https://assets.drivindealer.com/images/badges/low_lot_supply.png',
  'reason_name': 'Low Lot Supply'     
}
];